<?php
	$db = new SQLite3("data.db");



	$db->exec("CREATE TABLE IF NOT EXISTS users(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		email VARCHAR(255) NOT NULL, 
		passwort VARCHAR(255) NOT NULL,
		vorname VARCHAR(255) NOT NULL DEFAULT '',
		nachname VARCHAR(255) NOT NULL DEFAULT '',
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
	
?>